// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'color-scheme-DARK': string;
  'color-scheme-LIGHT': string;
  'text-block': string;
}
export const cssExports: CssExports;
export default cssExports;
