// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'cell': string;
  'custom-table': string;
  'table-body': string;
  'table-cell': string;
  'table-head': string;
  'table-head-cell': string;
  'table-row': string;
}
export const cssExports: CssExports;
export default cssExports;
